# Generated by Django 6.0.3 on 2026-04-29 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_network_alter_connection_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.AlterUniqueTogether(
            name='network',
            unique_together={('sender', 'receiver')},
        ),
    ]
