# Generated by Django 6.0.3 on 2026-05-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_reciever_network_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('job_type', models.CharField(default='Full-time', max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
